### PR TITLE
eslint-prettier

### PR DESCRIPTION
**Pull request by brittneypostma**

### CODE REVIEW

**Comment by brittneypostma** [comment]
This one just adds prettier and eslint and the config files to the app.

**Review by iisisrael — CHANGES_REQUESTED** [review]
✅ = Passed; ❌ = Failed; ❓ = Could not test

* ✅ Dependencies install without error
  * 11 vulnerabilities (3 low, 8 high) - to be fixed in a separate issue, includes breaking changes
* ❌ Linter can be run
  * Per the [usage](https://www.npmjs.com/package/eslint#installation-and-usage) steps, running `./node_modules/.bin/eslint src/` results in "ESLint couldn't find the config "eslint-recommended" to extend from"
  * I tried running `./node_modules/.bin/eslint --init`, selecting what I thought were the best options, and that resulted in new dependencies added to `package.json` and a new `.eslintrc.json` file created (not sure why it didn't just update the existing `.eslintrc`)
  * This then ran successfully, but resulted in found errors - these may have been a result of me selecting the wrong options, or if true errors, they can be resolved in a separate issue
  * I then backed out the changes, and for giggles renamed `.eslintrc` to `.eslintrc.json`, but that ran with the same error as the first attempt
* ❌ Prettier can be run
  * Per the [CLI instructions](https://prettier.io/docs/en/cli.html), I ran `npx prettier -c src/` - this identified eight files with problems (which can be resolved in a separate issue), but then exited with an error
  * The relevant tail of the logs:
```
...
20 timing npm:load Completed in 10ms
21 timing command:exec Completed in 366ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/home/israel/.nvm/versions/node/v15.8.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (node:events:378:20)
22 verbose stack     at maybeClose (node:internal/child_process:1067:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
23 verbose pkgid israel-j-carberry-says-hello-world@0.3.0
24 verbose cwd /home/israel/Documents/code-review/helloworld
25 verbose Linux 5.4.0-65-generic
26 verbose argv "/home/israel/.nvm/versions/node/v15.8.0/bin/node" "/home/israel/.nvm/versions/node/v15.8.0/lib/node_modules/npm/bin/npm-cli.js" "exec" "--" "prettier" "-l" "src/"
27 verbose node v15.8.0
28 verbose npm  v7.5.4
29 error code 1
30 error path /home/israel/Documents/code-review/helloworld
31 error command failed
32 error command sh -c prettier "-l" "src/"
33 verbose exit 1
```
* ✅ Tests pass

**Comment by iisisrael** [comment]
On the Eslinter check, I got the same error when running in Sublime Text on a single file, "Error: Failed to load config "eslint-recommended" to extend from."

**Comment by iisisrael** [comment]
On the Prettier check, I did get it to run successfully in Sublime Text without error, so this isn't a critical an issue.  It would be nice if it could be resolved easily, but spending too much time on it probably isn't worth the effort.

**Comment by brittneypostma** [comment]
I removed the line that was causing the error from the .eslintrc file. It should run now.

**Review by iisisrael — CHANGES_REQUESTED** [review]
✅ = Passed; ❌ = Failed; ❓ = Could not test

* ❌ Linter can be run
  * As updated, the error message is now "ESLint couldn't find the config "react-app" to extend from."
  * I tried removing that from `.eslintrc`, and the next error was "ESLint couldn't find the plugin "eslint-plugin-react"."  But this time it was more helpful and suggested I run:
    ```
    npm install eslint-plugin-react@latest --save-dev
    ```
  * So I ran that, then the linter could run (`./node_modules/.bin/eslint .`)
  * I then duckducked stuff, and it seems these are valid instead:
    ```
    "extends": ["eslint:recommended", "plugin:react/recommended", "plugin:prettier/recommended"],
    ```
* ✅ Prettier can be run
  * Since the docs for this said to run via `npx ...`, I tried the same running eslint, and got the same exit code error.  So I retried running prettier directly from `node_modules/` rather than with `npx`, and lo and behold, it ran without an exit error code (`./node_modules/.bin/prettier -c src/`)

**Comment by iisisrael** [comment]
With the `eslint-plugin-react` package installed and the `"extends"` config updated, this also runs fine via Sublime Text plugin.

**Comment by brittneypostma** [comment]
Is there something else you needed changed with this pr, I couldn't really tell from your comment what the issue was?

**Comment by iisisrael** [comment]
Yes, thanks for asking!  Sorry my code review wasn't clear.  I think `.eslintrc` needs this line instead:
```
"extends": ["eslint:recommended", "plugin:react/recommended", "plugin:prettier/recommended"],
```

And this needs installed on the project:
```
npm install eslint-plugin-react@latest --save-dev
```

My guess is that you may have some npm packages installed globally, or installed as dependencies of your IDE and that path is exported globally, resulting in project dependencies not failing even when they aren't required in `package.json`.

**Pull request merged**
